apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-a.fullname" . }}
  labels:
    {{- include "service-a.labels" . | nindent 4 }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      {{- include "service-a.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
      labels:
        {{- include "service-a.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
            - name: ServiceA__BackendServiceName
              value: {{ .Values.backend.host | quote }}
            - name: ServiceA__BackendPort
              value: {{ .Values.backend.port | quote }}
            - name: JAEGER__AGENTHOST
              value: {{ .Values.jaeger.host | quote }}
            - name: JAEGER__AGENTPORT
              value: {{ .Values.jaeger.port | quote }}
          ports:
            - name: http-a
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 2
            httpGet:
              path: /healthz/liveness
              port: http-a
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 3
            httpGet:
              path: /healthz/readiness
              port: http-a
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
