apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    {{- include "service-a.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http-a
      protocol: TCP
      name: http
  selector:
    {{- include "service-a.selectorLabels" . | nindent 4 }}
